<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * If you want to change any configuration parameter, copy this file to the root folder
 * of your project. Skull will try to load your configuration file first, so you can set any configuration
 * parameter you want.
 */

// Database info
@define('SKULL_DB_DSN',				'mysql:host=localhost;dbname=skull');
@define('SKULL_DB_USER',			'root');
@define('SKULL_DB_PASSWORD',		'');

// Password
@define('SKULL_PASSWORD_SALT', 		'dlaejhdwieugr34712-13fkj3-122045*&@#$)*&Gkdf*%$@I&$fdfd');

// System params
@define('SKULL_DEBUG', 				true);
@define('SKULL_SESSION_NAME', 		'skullid');

@define('SKULL_VIEW_FOLDER',		dirname(__FILE__) . '/../view/html/');
@define('SKULL_VIEW_BASE',			'./view/html/');
?>
